require 'coveralls'
Coveralls.wear!
language: python
python:
  - "3.6"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m pytest --cov
after success:
  - coveralls
notifications:
  email:
    recipients:
      - mikeanguandia@yahoo.com
