language: python

python: 
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - pytest calc/test_calc.py --cov
  
after_success:
  - coveralls
