language: python

python: 
  - "3.6"

install:
  - pip install -r requirements.txt
  - pip install pytest
  - pip install pytest-cov
  - pip install coveralls

script:
  - python -m test_calc --cov
  
after_success:
  - coveralls
