language: python
python:
  - "3.7-dev"
# command to install dependencies
install:
  - pip install -r requirements.txt
# command to run tests
script:
  - python -m test_calc --cov
after success:
  - coveralls
notifications:
  email:
    recipients:
      - mikeanguandia@yahoo.com
